name: Flutter Build CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Create platform folders and fix Android minSdk
        run: |
          flutter create .
          git checkout lib/ pubspec.yaml || true
          # الحل الجذري لتغيير إصدار الأندرويد في فلاتر 3.24
          sed -i 's/flutter\.minSdkVersion/23/g' android/app/build.gradle

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
