name: Generate Android Folder

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Android Files
        run: flutter create .
          
      - name: Commit and Push Android Folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add android/
          git commit -m "إضافة مجلد الأندرويد رسميا للمشروع 🚀" || echo "No changes to commit"
          git push
